### ISSUE TITLE
Add MAXQDA collection

### ISSUE THREAD

**Issue by thkania** [tkainrad/keycombiner#101]
A public collection for MAXQDA would be nice. An official list with all shortcuts is available on their [homepage](https://www.maxqda.com/help-mx22/technical-data-and-information/keyboard-shortcuts).

**Comment by tkainrad** [comment]
Thanks for the suggestion, that's a very clean list, will add a collection!

**Comment by tkainrad** [comment]
The [MAXQDA collection](https://keycombiner.com/collections/maxqda/) is now live! Thanks again for the suggestion.
