### ISSUE TITLE
Can't remove personal collections from instant lookup's excluded collections

### ISSUE THREAD

**Issue by gregorias** [tkainrad/keycombiner#106]
I'd like to create personal key bindings instead of relying on public ones, but I'm hampered by not being able to configure Instant Lookup to show them. When I go to instant lookup's settings, I see that they in excluded collections:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/722385/228150970-855eaf9c-2f47-47d7-95df-4c80b2a02776.png">

And I see no option to get them out. Pressing CMD + Backspace or backspace doesn't work.

**Comment by gregorias** [comment]
I just now understood how that list works:
- All collections are deselected (and therefore NOT excluded) by default.
- Only selected collections are excluded. A non-white background tells which collections are selected.

**Comment by tkainrad** [comment]
That's exactly how this works. Sorry that this was confusing. It's probably not the most sophisticated way of doing multi-selection :grimacing: 
I might extend the help text to make this more clear.
