### ISSUE TITLE
Option to hide collection from instant lookup

### ISSUE THREAD

**Issue by yangkennyk** [tkainrad/keycombiner#12]
**Is your feature request related to a problem? Please describe.**
I have a collection that I set up but decided to not use the app I set it up for but I also don't want to delete the collection in case I decide to use it again. So it would be nice to be able to hide the collection from the quick lookup

**Describe the solution you'd like**
Option to hide/disable a collection

**Describe alternatives you've considered**
None

**Additional context**
No

**Comment by tkainrad** [comment]
That's a great suggestion, thanks!

I have been wanting to add customization options for the instant lookup. This is a good one that's also relatively easy to implement.

**Comment by tkainrad** [comment]
Added it to the To-Do column of the project board. Should be done within a few weeks.

**Comment by tkainrad** [comment]
Took a bit longer than I thought, but it's now done! It is available for Pro users.

It is implemented as a multi-selection select-box. This is how it looks like for me:

![image](https://user-images.githubusercontent.com/7394822/116777040-50940580-aa6c-11eb-920b-45dab1d16b6d.png)

There will be a lot more settings to customize the instant lookup soon.

Thanks again for the suggestion!
