### ISSUE TITLE
Add dropdown arrows to toolbar menu buttons

### ISSUE THREAD

**Issue by slt-uxd** [tkainrad/keycombiner#14]
For example, I did not realize that the "Copy" button was actually a menu showing more options, so I didn't bother to click on it.

**Comment by tkainrad** [comment]
That's an interesting suggestion. I guess you are right, dropdown icons would improve accessibility. We just have to check if the buttons would still look reasonably well and if their size would still fit on mobile devices.

Added the issue to the project board.

**Comment by slt-uxd** [comment]
Should be ok. Yeah I do UI for a living, so I tend to catch these kinds of
issues :)

Here's another one - I love the visualizing feature, but the color stripes
on the keys make the text on the keys difficult to read:

[image: image.png]

Two reasons: 1) The contrast between the two colors clash 2) The contrast
between the colors and the white text isn't high enough.

It is important to be able to easily read that text quickly at a glance.
This should easily be fixable however, by simply darkening the colors,
which you could do programmatically/dynamically without changing the actual
color values. Try lowering the brightness by at least 25%. For example:

[image: image.png]

Maybe even a bit more, without losing the color. It will also diminish
the clash in colors. At some point however it becomes too subjective as we
all see colors slightly differently anyhow. But the main point is contrast,
so that the text is more readable.

On a separate note, the import CSV feature is great! Saved me a lot of
time.

Sebastien

**Comment by tkainrad** [comment]
Thanks for these suggestions!

I think something went wrong uploading your images. In case you still have them around, it would be great if you could upload them again.

We did play around with the coloring quite a bit. Not so easy to find a set of colors where each color works well individually and also together with the other ones. Also, different browsers and operating systems render the text a bit differently, which plays a role as well. Still, happy to take another look.

**Comment by slt-uxd** [comment]
Sorry, just saw this! See attached.

I actually like the white text on black key the best, and I don't think I
even need any coloring to be honest. My mind already cannot process too
many things... name of modifier, visual location of modifier, key name,
location of key, command name), and so adding colors to the mix, while it
may seem useful, may actually have the effect of making it harder to
visualize, due to cognitive overload.

Because the main goal here is to visually associate two things only: 1) the
location of the pressed keys, and 2) the command (the text on the keys),
the priority should be to make these two things as identifiable as
possible, and for the text, it means readability.

As such, perhaps consider having a "high contrast" option which would just
show white text on black keys, maybe not even bothering with colors. Doing
this will also make your visualizer more accessible.

Hope this helps :)

Sebastien

**Comment by tkainrad** [comment]
Hmm, still can't see the images. I think GitHub does ignore them when commenting via email reply. You can send them via regular mail if you want, I believe you know my mail address ;)

I think you have a good point. When grasping an entirely new collection, the colors can be quite useful to understand how the application uses modifiers. However, for working with your own shortcut collections, the colors often don't add much value. Having such an option sounds interesting, I create an issue!

**Comment by tkainrad** [comment]
The dropdown arrows are now live, thanks again for the suggestion!

![image](https://user-images.githubusercontent.com/7394822/114743963-7a9bb700-9d4d-11eb-8a42-fbd69a4129d1.png)

**Comment by slt-uxd** [comment]
Awesome! Or should I say... wünderbar!
