### ISSUE TITLE
Could not read preferences.json with Windows 7 and keycombiner 0.3.0

### ISSUE THREAD

**Issue by Dra9o** [tkainrad/keycombiner#22]
Error:
```TypeError: Error processing argument at index 0, conversion failure from 
    at C:\Users\Yaroslav\AppData\Local\Programs\keycombiner\resources\app.asar\webpack:\src\main\index.js:729:20
    at FSReqCallback.oncomplete (fs.js:160:23)
```
OS: Windows NT 6.1.7601

**Comment by tkainrad** [comment]
Hi, thank you very much for submitting this bug report!

Would you mind giving me a bit more context? It looks like the problem occurred when trying to read the local settings file that stores the instant lookup trigger shortcut.

Did this happen only once or does it always happen for you when trying to change the lookup trigger shortcut? Is there anything else you can share that might help me reproduce your problem on my machine?

Thanks!

**Comment by tkainrad** [comment]
Unfortunately, I have not been able to reproduce this issue. I will leave it open for a couple more days and will then close. Feel free to open again if there is more information.

**Comment by Dra9o** [comment]
This happened every time KeyCombiner was launched. Perhaps due to the fact that two copies of the program were launched (it does not check its status at startup).
I was unable to reproduce this error again, it may have disappeared due to a system reboot.

**Comment by tkainrad** [comment]
Thank you very much for these additional insights.

I still cannot reproduce it, even with running multiple instances. However, you have a great point. I don't see why KeyCombiner should allow multiple instances. KeyCombiner 0.3.1 will switch to the main window of the already launched instance when trying to launch another instance. See #23

**Comment by tkainrad** [comment]
KeyCombiner now makes sure that only one instance is run in parallel! I think this resolves this issue.
