### ISSUE TITLE
Shortcut Visualizer not working on macOS

### ISSUE THREAD

**Issue by LandonRGeorge** [tkainrad/keycombiner#31]
**Describe the bug**
None of the keyboard shortcuts in my collection are displaying correctly within the Shortcut Visualizer. 

For some of my collections, the visualizer appears to be substituting the `Ctrl` key for the `Cmd` key:
![CleanShot 2021-10-01 at 04 58 11](https://user-images.githubusercontent.com/48839396/135602548-fdec978c-1dc7-4145-b3cc-72a33732e97f.png)

For other collections, the visualizer does not render any keyboard combinations:
![CleanShot 2021-10-01 at 05 06 02](https://user-images.githubusercontent.com/48839396/135602823-18e02df3-d2b3-4c8c-aae6-c947bdf90d4f.png)

**Additional context**
- I am experiencing this behavior on desktop version 0.3.3, as well as the web version.
- I am running macOS Big Sur, version 11.6

**Comment by tkainrad** [comment]
Argh, that's a serious bug, thanks a lot for reporting it!

It should be fixed now, please try again.

**Comment by LandonRGeorge** [comment]
It's working now, thank you!

**Comment by tkainrad** [comment]
Glad to hear that, thanks for reporting back!
