### ISSUE TITLE
Allow to hide certain areas of the UI

### ISSUE THREAD

**Issue by tkainrad** [tkainrad/keycombiner#35]
Requested via mail

To save screen space, some users would like to hide parts of the UI, especially during practice. Primarily, these would be the side navigation and the top navigation bar.

**Comment by doctopus** [comment]
If the hiding of elements could be saved to be persistent for an user, it would be nice as one does not have to do the adjustments every time one opens the Mac app.

**Comment by tkainrad** [comment]
Absolutely, the app would have to remember the state of the UI. This would work similar to how the personal collection list in the side-nav can currently be collapsed. KeyCombiner remembers the collapsing state.

However, I fear like you would have to re-enable the side-nav frequently as you pretty much need it for navigation around the site.

**Comment by tkainrad** [comment]
This just went live!

You can now hide the side navigation:

![hide-side-nav](https://user-images.githubusercontent.com/7394822/149675958-1c9732d3-20f9-4100-af14-fcf53a9877e6.gif)


Furthermore, the top navigation bar is now thinner when logged in.
