### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by tkainrad** [tkainrad/keycombiner#40]
Requested via mail

Many users prefer a dark mode, especially developers. This issue should help to figure out how large the demand is.

**Comment by msemialjac** [comment]
I would like to upvote this issue and try to (hopefully) make some helpful suggestions (although I am not sure how applicable those are).

I am a heavy user of Dark Mode in all apps and Web locations to the point that if the app doesn't have an official Dark Mode I use the Linux color inverter tool xrandr-invert-colors (https://github.com/zoltanp/xrandr-invert-colors)

I am not sure how your app works internally, but here are a couple of suggestions that (if applicable to your app) might be useful:
- If you have colors of your default Light color scheme kind of centralized (or at least in the same locations for different parts of the program) you could run it through some color inverter tool (there are plenty available online and offline - here is an example: [https://colorinverter.imageonline.co/](https://colorinverter.imageonline.co/)) to get inverted RGB values
- For a quick preview of how it would look inverted you could use mentioned xrandr-invert-colors tool for Linux (results would be applicable across the OS-es, I guess)
- Based on the previous 2 steps you can identify "bad" inverted colors, and for those colors find appropriate alternatives

That's it. I would just like to add in regards to OP - it is not just developers (although I am barely in that category), but an increasing number of "regular" users who are switching or using Dark Mode more heavily. In the last couple of months, 3 websites that I visit regularly have added the Dark Mode option. And 2 of those websites are having a huge visit count (I don't know specifics but I am sure one of those sites has 1M+ visitors within 1 week or less). None of these 3 websites are aimed at developers!

PS - I am a Key Combiner Pro user, and regardless of Dark Mode or not - I want to encourage you to keep up the good work ;-)

**Comment by tkainrad** [comment]
Hi @msemialjac 

Thanks a lot for these insights! I am pretty sure that there will be a KeyCombiner dark mode. Not sure yet if it will be within 1 month or 1 year though. You adding your vote as a _Pro_ user definitely counts!

**Comment by tkainrad** [comment]
Happy to announce that I am now working on this. Hopefully, _Dark mode_ will be available within April.

**Comment by msemialjac** [comment]
Thanks Thomas :)

I forgot that there is no dark mode in the meantime.

I’ve made full-screen i3 scratchpad for key-combiner, and when I launch it - it inverts color with xrandr-inverter (just for display with scratchpad), and it returns to normal (non-inverted) colorscheme when I minimize scratchpad…

Only reminder that is not dark mode is inverted bumblebee-statusbar. And that will go to soon…

Thanks once again. Keep up the god work.

Kr,
MSB

Poslano s mojeg iPhonea

**Comment by tkainrad** [comment]
Dark Mode is now live :partying_face: 

![image](https://user-images.githubusercontent.com/7394822/166189834-edd9c1ee-f3ef-45fa-9e16-1e591f9fad3a.png)
![image](https://user-images.githubusercontent.com/7394822/166189896-0c4abae9-be6c-4952-b1c5-6c6d270476b0.png)

If there are any UI glitches with dark mode, I'd be happy to hear about and fix them!

**Comment by msemialjac** [comment]
Thanks a bunch Thomas ; - ) 

I’ll check it out.

Kr,
MSB
