### ISSUE TITLE
Add sorting options to Dashboard

### ISSUE THREAD

**Issue by y-vasyunin** [tkainrad/keycombiner#45]
I'd like to be able to manually rearrange my personal collections, according to my study priorities.

Another option would be to have an alphabetical sorting. In the screenshot below, I added a numerical prefix to every collection, but KeyCombier doesn't consider it.

<img src="https://user-images.githubusercontent.com/18553297/136752310-85e02f8a-a2c8-4e6c-ac2a-52a879153afc.png" width="500px">

**Comment by tkainrad** [comment]
Hi again, @y-vasyunin,

I am happy to announce that you can now order your personal collections directly from your dashboard!  
Simply drag and drop any collection to the desired position. The updated order will be reflected in the side navigation and the instant lookup once the page gets reloaded.

The order of collections in the instant lookup was seemingly random before, it now follows the set order.

![sort-collections](https://user-images.githubusercontent.com/7394822/137200990-68c1757c-e704-4c4a-82a1-6e34522c743a.gif)

---
PS: Inspired by your screenshot, I added [a public collection for Calibre](https://keycombiner.com/collections/calibre/). I believe it is the only resource that also has all the shortcuts of the integrated E-book viewer.
