### ISSUE TITLE
Add ability to edit keys for a different OS

### ISSUE THREAD

**Issue by y-vasyunin** [tkainrad/keycombiner#49]
Let's say I work on a Windows laptop and I create a new personal collection from scratch. While adding new entries, it would be useful to have an option to provide keys for Mac as well. Of course, in this case I would have to type them - no _Record_ option would be available.

**Comment by tkainrad** [comment]
This is now possible:

![image](https://user-images.githubusercontent.com/7394822/188315006-18ed0d2e-a971-4475-8755-449844700264.png)

Sorry for the long wait :grimacing: 

There will be more advanced features for people using multiple operating systems in the near future.
