### ISSUE TITLE
Left-click on the icon in Windows 10 tray bar (taskbar) does not do anything

### ISSUE THREAD

**Issue by y-vasyunin** [tkainrad/keycombiner#53]
Normally, as with other apps, I'd expect that a single or double click on a tray icon shows me the application window. In the case of KeyCombiner, nothing happens.
![image](https://user-images.githubusercontent.com/18553297/140021499-59b68a84-fda8-4ea9-a031-fc3a65bb0828.png)

**Comment by tkainrad** [comment]
Thanks for this report! I am dependent on them to get these details right on all three desktop platforms.

I will look into it for the next release due in a couple of weeks. I agree that it should open via left-click also, this is how it behaves on Linux and macOS.

**Comment by y-vasyunin** [comment]
Right clicks work fine. I think, with the left click, it would be great to show the KeyCombiner app, or let the user decide what action he/she wants to perform with a left click.

**Comment by tkainrad** [comment]
That sounds good, too. I will do a bit of research on how other apps behave on Windows. I guess the options are:

- Show context menu
- Show instant lookup
- Show the main window
- Have a setting to let the user decide which of the above should happen

The current behavior of doing nothing is definitely suboptimal.

**Comment by tkainrad** [comment]
The new KeyCombiner Desktop version 0.5.0 just went live! In this version, both single- and double-left-clicks open the KeyCombiner main window on Windows.

Thanks again for the suggestion!
