### ISSUE TITLE
No return to the dashboard after updating a payment method

### ISSUE THREAD

**Issue by y-vasyunin** [tkainrad/keycombiner#54]
After I updated the payment details in the desktop app, I see no way to get back to the main app screen. It's a bit frustrating. So I had to close the window and reopened the app.
<img src="https://user-images.githubusercontent.com/89078164/141283942-6fc9f556-5e72-438b-ae0c-9af67a112519.png" width=50% height=50%>
I'm on Windows 10, KeeCombiner 0.4.0.

**Comment by tkainrad** [comment]
Thanks for reporting this. You are absolutely right, that is very annoying. 

I think I will be able to redirect back to the checkout page upon successfully changing the payment details. However, this will still be a problem when you want to cancel the editing. Fixing that will take a bit longer.

In any case, if you ever find yourself stuck again somewhere, you can use <kbd>alt</kbd>+<kbd>left</kbd>/<kbd>right</kbd> to navigate back and forth. This would have taken you back to KeyCombiner.

**Comment by tkainrad** [comment]
The flows for updating payment details and canceling the subscriptions are now shown as overlays, similar to the flow for purchasing a new subscription:

![image](https://user-images.githubusercontent.com/7394822/141677733-e5d7f598-3247-400d-b263-e4f390c930b6.png)

Therefore, they can now be canceled via the <kbd>x</kbd> button in the top right. After successfully doing these operations, you will now be back at the checkout page. 

Thanks for submitting this issue, this was definitely a much-needed improvement!
