### ISSUE TITLE
Error report for keycombiner 0.3.2 failing to update to 0.5.0

### ISSUE THREAD

**Issue by elchead** [tkainrad/keycombiner#58]
Error:
```
Error: ENOENT: no such file or directory, rename '/Users/adria/Library/Application Support/Caches/keycombiner-updater/pending/temp-KeyCombiner-0.5.0-mac.zip' -> '/Users/adria/Library/Application Support/Caches/keycombiner-updater/pending/KeyCombiner-0.5.0-mac.zip'
```
OS: macOS 10.17

**Comment by tkainrad** [comment]
Hi, thanks for filing this issue. I suppose you managed to resolve it yourself? Did you have to update manually to 0.5.0?

Btw, maybe you noticed that the error message was not properly shown here in the issue. This is fixed in the new version 0.5.0. I fixed it manually in this issue.
