### ISSUE TITLE
Updating the app logs me out on Windows

### ISSUE THREAD

**Issue by y-vasyunin** [tkainrad/keycombiner#59]
I don't know whether it's intentional or not. After updating to v0.5.0 (Windows), I was logged out. The same was with previous updates. Shouldn't users keep their login active? Is there also a way to implement silent updates in background that doesn't disturb the use of the app?

**Comment by tkainrad** [comment]
Hi, thanks for reporting this, it really does sound annoying!

I am briefly testing all updates also on Windows. However, I was already logged out before updating so I didn't think much of it when I was not logged in after the update. On Linux, the login definitely remains active. I will investigate for next month's release!

A completely silent update will probably not be possible though. Ideally, you will be notified on app start that an update has been downloaded and is available. Then, whenever you feel like it, you can restart the app to apply the update.

**Comment by tkainrad** [comment]
Good news: The problem should now be resolved!

KeyCombiner sessions were valid for 2 weeks. This did not matter as long as the desktop app stayed open. However, updating requires a restart which then caused the session expiration check to log you out.

Starting now, every session that is started from the desktop app with _Remember Me_ checked will be valid for 2 years. The 2 weeks validity is still in effect for web sessions. Unfortunately, this only goes for new sessions. So, you will probably be logged out one last time with next month's update :see_no_evil:
