### ISSUE TITLE
Select multiple combination on touchscreen devices without keyboard

### ISSUE THREAD

**Issue by tkainrad** [tkainrad/keycombiner#6]
Reported via mail

**Is your feature request related to a problem? Please describe.**
It is currently not possible to select multiple key combinations on mobile devices without a physical keyboard, because neither shift nor drag-selection work. Therefore, the _Practice Selection_ feature is unusable on tablets that are large enough for text snippet practice.

**Describe the solution you'd like**
Select multiple combinations by simply clicking on them. Additional clicks should not destroy the previous selection.

**Comment by tkainrad** [comment]
Implemented now. If KeyCombiner detects a touchscreen as main input device, click selection will not destroy the previous selection. Deselecting still works via the respective toolbar button.

**Comment by QueensDeeJay** [comment]
Yay!!! Thank you, Thomas. **This is huge**, as it opens the door to truly **practical** use of KC on an iPad. Wonderful!  Wonderful! Wonderful!

**Comment by tkainrad** [comment]
You are welcome! Thank you for this comment. Glad this solves the problem for you.
