### ISSUE TITLE
Update message on autostart after reboot is confusing

### ISSUE THREAD

**Issue by y-vasyunin** [tkainrad/keycombiner#68]
After rebooting my computer, a message popped up asking me to update the app. If I read it correctly, from the message it wasn't clear that it's about KeyCombiner. I was even thinking of some malware because recently I had problems with it. I suggest to update the message text.

**Comment by tkainrad** [comment]
That's a great report, thx!

I also don't like the message on system startup and was thinking about how to show it only when the user focuses on the KeyCombiner main window. As that isn't so easy I postponed it. Not sure why I didn't think of just changing the message. I will definitely do that for the next release!

**Comment by tkainrad** [comment]
This is now live in 0.7.0, thanks again for the suggestion!
