### ISSUE TITLE
Error report for keycombiner 0.3.4

### ISSUE THREAD

**Issue by s0538500** [tkainrad/keycombiner#69]
Error:
```
TypeError: Error processing argument at index 0, conversion failure from 
    at /Applications/KeyCombiner.app/Contents/Resources/app.asar/webpack:/src/main/index.js:898:20
    at FSReqCallback.oncomplete (fs.js:160:23)
```
OS: macOS 10.17

**Comment by tkainrad** [comment]
Hi, thanks for reporting your problem! @s0538500 

I believe this was already reported and solved. It previously happened when you set an invalid or empty instant lookup trigger. Please see #55 and update to the latest KeyCombiner Desktop version via _File->Check for Updates_
