### ISSUE TITLE
Cannot Delete Previously-Created Google SSO Account

### ISSUE THREAD

**Issue by brimwats** [tkainrad/keycombiner#75]
Hello! 

continued from #74 

I went to delete the account created by the google SSO in order to merge it with my KC account. When I go to delete account it asks me to login with a password. There wasn't a password made with the SSO account.

**Comment by brimwats** [comment]
alternatively you could feel free to delete the newer account :)

**Comment by tkainrad** [comment]
Hi, 

I remember thinking briefly about this when implementing the account deletion. I thought this should be a rare enough use case that it should be fine if users had to set a password before being able to delete an account. So, to delete the account, please set a password first via _Settings->Password Settings_.

Alternatively, if you want me to delete it, please send an email to support@keycombiner.com using the Gmail account that you signed up with.
