### ISSUE TITLE
Import the collection from CSV

### ISSUE THREAD

**Issue by Drakula44** [tkainrad/keycombiner#82]
**Is your feature request related to a problem? Please describe.**
Ok, I saw vim public but I did not like that it is not properly formatted. (sequences are not really sequences and like upper letters are not shift + lower letter. So I wanted to like export it and then write a script that will fix that in CSV and then reupload it so I have a private VIM cheat sheet as I wanted.

**Describe the solution you'd like**
Have an import button when creating a new collection or inside an already existing collection. (first one is probably easier to implement

PS:
I will post a few more features or bugs as I really like the software and will try to make great use of it. Thanks for the work.

**Comment by Drakula44** [comment]
Never mind I am just blind thanks anyway.

**Comment by tkainrad** [comment]
Glad you have found the feature! I have had a few people ask the same. I should probably advertise the CSV import a bit more. Thanks for submitting this issue!
