### ISSUE TITLE
Add GeoGebra collection

### ISSUE THREAD

**Issue by s0rlie** [tkainrad/keycombiner#86]
GeoGebra  is one of the most popular free digital tools for teaching and learning math.

Keyboard shortcuts available on this [GeoGebra Keyboard Shortcuts](https://wiki.geogebra.org/en/Keyboard_Shortcuts)

**Comment by tkainrad** [comment]
Thanks, that is a great suggestion! Will add it shortly.

**Comment by tkainrad** [comment]
It took a bit longer than I would have liked, but here it is, the [new public GeoGebra collection](https://keycombiner.com/collections/geogebra/).
