### ISSUE TITLE
On spaced repetition review page, for mistyped combinations, be able to easily see which collection they belong to

### ISSUE THREAD

**Issue by HarryLang100** [tkainrad/keycombiner#89]
Sometimes, I have a combination that exists in multiple collections. On the spaced repetition review page, it is not easy to see which collection the one belongs to that I got wrong. Could it be shown in the pink boxes?

![image](https://user-images.githubusercontent.com/10622188/188950745-4cb0ba3b-7c50-4016-aed1-669b8ffe647f.png)

**Comment by tkainrad** [comment]
Huh, I missed this one, sorry! This is a very reasonable request that I will implement shortly.

Thanks for surfacing this!

**Comment by tkainrad** [comment]
This is now live! The collection name will show after daily reviews or when combinations have been sourced from multiple collections via selecting from the combined collection.

![image](https://user-images.githubusercontent.com/7394822/209963467-d2daaf67-7a19-419a-914d-3c8da5e20a2c.png)

Thanks again for the request!
