### ISSUE TITLE
Cannot remove categories from shortcuts on the Windows desktop app

### ISSUE THREAD

**Issue by mikegomezg** [tkainrad/keycombiner#92]
**Describe the bug**
I can't type '-remove-' in the choice list on the Windows app to remove a category from a shortcut. I have to do it on the web app.

**To Reproduce**
1. Select a shortcut in the windows app with a category assigned.
2. Click the 'edit' button
3. Try to type '-remove-' to remove the shortcut.
4. The choice list doesn't let you type in it.

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**Additional context**

**Comment by mikegomezg** [comment]
reinstalled app and that seemed to fix the problem

**Comment by tkainrad** [comment]
Thanks for submitting this issue!

Hmm, interesting. If reinstallation fixed it, I think a simple restart would have probably done the trick also.

In addition, please note that you can also remove the category from a single shortcut by clicking on the shortcut row's edit button on the right and then simply clearing the category field.
