### ISSUE TITLE
make it easier to enter new shortcuts - automatically set focus on description field in dialog

### ISSUE THREAD

**Issue by mikegomezg** [tkainrad/keycombiner#93]
**Is your feature request related to a problem? Please describe.**
It should be easier to enter new shortcuts in the UI. I know you can batch import them but I like to add shortcuts as I learn more about a program

**Describe the solution you'd like**
When I go to enter / edit a shortcut by bringing up the "Edit Key Combination" dialog, is it possible to set the focus on the description field? Then I could enter a shortcut without having to touch the mouse. Right now, it is unclear where the focus goes when the dialog shows up. Sometimes if I press tab a few times, it will go to the description field, but other times the focus remains on the web page behind the dialog.

**Describe alternatives you've considered**
Usually I just use the mouse to set the focus on the description field. I also will sometimes change focus from the app and then switch back and usually the focus gets close to the dialog page.

**Additional context**
Once I have focus on the description field, I can tab to the other fields pretty quickly. Having to keep setting the focus with the mouse gets tedious.

**Comment by tkainrad** [comment]
Oh wow, you are absolutely right. The initial focus should be on the description field! I will make that change.

**Comment by tkainrad** [comment]
This is now live :partying_face: 

![kc-modal-autofocus](https://user-images.githubusercontent.com/7394822/205440766-f0a5f4e4-b698-4982-a64e-3a7b8feba5de.gif)

Thanks again for the suggestion!

**Comment by tkainrad** [comment]
This is now live :partying_face: 

![kc-modal-focus](https://user-images.githubusercontent.com/7394822/205440834-bec29fd0-c721-4953-bf03-ba635382b39d.gif)

Thanks again for the suggestion!
