### ISSUE TITLE
Practice session not accepting keyboard input

### ISSUE THREAD

**Issue by mikegomezg** [tkainrad/keycombiner#99]
**Describe the bug**
When I start a practice session on either the desktop app or the web app, the page doesn't respond when I type.

**To Reproduce**
1. Go to a collection.
2. Select some combinations.
3. Click "Practice Selection"
4. Notice that the page doesn't receive any input.

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**Additional context**

**Comment by dclarktandem** [comment]
I am having the same issue on Mac OS on an M1 Mac running Ventura 13.1.

**Comment by tkainrad** [comment]
Argh, I am sorry. That was yesterday's supposedly tiny behind-the-scenes update gone very wrong. It should be fixed now. Thanks for reporting it quickly.
